"""Static corpus-studied data: authors and works already analyzed in corpus papers."""

CORPUS_STUDIED = [
    {"author": "Paul Celan", "works": ["Holocaust poetry", "Negative poetics"], "studied_by": "Daniel Feldman (2014)"},
    {"author": "Dan Pagis", "works": ["Holocaust poetry", "Testimonial silence"], "studied_by": "Feldman (2014), Yacobi (2005)"},
    {"author": "Rosario Ferr\u00e9", "works": ["Self-translation (English/Spanish)", "Cannibalized language"], "studied_by": "Olga Blomgren (2025)"},
    {"author": "\u00c9douard Glissant", "works": ["Translation as Relation"], "studied_by": "Sandra Bermann (2014)"},
    {"author": "Lawrence Durrell", "works": ["Orientalism in the Alexandria Quartet"], "studied_by": "James Gifford (1999)"},
    {"author": "Joseph Conrad", "works": ['"Amy Foster"', '"Prince Roman"', "Polish-English language politics"], "studied_by": "Juliette Bretan (2025)"},
    {"author": "Henry Highland Garnet", "works": ["Abolitionist orations", "Black Romanticism"], "studied_by": "Charline Jao (2025)"},
    {"author": "H.L.V. Derozio & Kasiprasad Ghosh", "works": ["Anglo-Indian Persianate poetry"], "studied_by": "Humberto Garcia (2025)"},
    {"author": "Edward Said", "works": ["Freud and the Non-European", "Orientalism"], "studied_by": "Khanna, Edelman, Mukherjee, Reilly, Al-Kassim (2025)"},
    {"author": "Gayatri Chakravorty Spivak", "works": ["Death of a Discipline", "Planetarity"], "studied_by": "Khanna/Spivak conversation (2025)"},
    {"author": "Naz\u0131m Hikmet", "works": ["Poetry in China", "Bandung/Asiafrica solidarity"], "studied_by": "Alice Xiang (2025)"},
    {"author": "Ricardo Aleixo & Arthur Bispo do Ros\u00e1rio", "works": ["Brazilian concretism", "Black Brazilian poetics"], "studied_by": "Jane Kassavin (2025)"},
    {"author": "Jean M\u00e9tellus", "works": ["Anacaona (historical drama)"], "studied_by": "Xavier Lee (2025)"},
    {"author": "Aphra Behn", "works": ["Oroonoko: The Royal Slave"], "studied_by": "Xavier Lee (2025)"},
    {"author": "Joan Anim-Addo", "works": ["Imoinda (opera adaptation)"], "studied_by": "Xavier Lee (2025)"},
    {"author": "Sulaiman Addonia", "works": ["Silence Is My Mother Tongue"], "studied_by": "Akshya Saxena (2025)"},
    {"author": "Jacinta Kerketta", "works": ["Angor (Embers)"], "studied_by": "Akshya Saxena (2025)"},
    {"author": "Shakespeare", "works": ["Measure for Measure", "Falstaff / Henry IV"], "studied_by": "Braider (2025), Deutermann (2025)"},
    {"author": "Ovid / Guillaume de Lorris / Jean de Meun", "works": ["Roman de la Rose", "Metamorphoses (Pygmalion)"], "studied_by": "Hicks-Bartlett (2025)"},
    {"author": "William Gardner Smith", "works": ["The Stone Face"], "studied_by": "Nyawalo (2025)"},
    {"author": "Futabatei Shimei", "works": ["Ukigumo (Floating Cloud)"], "studied_by": "Bonnie Pang (2025)"},
    {"author": "Intan Paramaditha", "works": ["Gentayangan"], "studied_by": "Jennifer Goodlander (2025)"},
    {"author": "Virginia Woolf", "works": ["Between the Acts"], "studied_by": "Tianyi Shou (2025)"},
    {"author": "Xiao Hong", "works": ["Hulan He Zhuan (Tales of Hulan River)"], "studied_by": "Tianyi Shou (2025)"},
    {"author": "Theresa Hak Kyung Cha", "works": ["White Dust from Mongolia"], "studied_by": "Vero Chai (2025)"},
    {"author": "Cervantes", "works": ["Don Quixote (Romantic approach)"], "studied_by": "Gilbert-Santamaria (2025)"},
    {"author": "Francisco Balagtas", "works": ["Florante at Laura"], "studied_by": "Kelly (2025)"},
    {"author": "Mao Zedong", "works": ["Classicist poetry / fake Mao poems"], "studied_by": "Zhiyi Yang (2025)"},
    {"author": "Henry David Thoreau", "works": ["Walden (gender & ecology)"], "studied_by": "Rachael DeWitt (2025)"},
    {"author": "Chaucer", "works": ["The Franklin's Tale (Dorigen)"], "studied_by": "Bartlett & Crocker (2025)"},
    {"author": "James Baldwin", "works": ["Go Tell It on the Mountain", "Another Country"], "studied_by": "Mikko Tuhkanen (2025)"},
    {"author": "Omar El Akkad", "works": ["American War"], "studied_by": "Lydia R. Cooper (2025)"},
    {"author": "Jorge Isaacs", "works": ["Mar\u00eda (Romantic hero, Colombia)"], "studied_by": "Mercedes Lopez Rodriguez (2025)"},
    {"author": "Viktor Shklovsky", "works": ["Theory of parody", "Italian reception", "Formalism"], "studied_by": "Lipovetsky, Tripiccione, Kalinin (2025)"},
    {"author": "Yuri Tynianov", "works": ["Literary evolution theory"], "studied_by": "Oushakine (2025)"},
    {"author": "Kazimir Malevich & Velimir Khlebnikov", "works": ["Futurism/Formalism", "Linguistic aesthetics"], "studied_by": "Dennis Ioffe (2025)"},
    {"author": "Flaubert", "works": ["Novembre", "Madame Bovary (gender)"], "studied_by": "B\u00e9langer/Brassard (2025)"},
    {"author": "Rachilde", "works": ["Monsieur V\u00e9nus"], "studied_by": "Elinor Knutsen (2025)"},
    {"author": "Georges Rodenbach", "works": ["Bruges-la-Morte"], "studied_by": "Elinor Knutsen (2025)"},
    {"author": "George Sand", "works": ["Indiana", '"La Marquise"'], "studied_by": "Sophie M\u00e9nard (2025)"},
    {"author": "\u00c9mile Zola", "works": ["La Cur\u00e9e (lesbianism)"], "studied_by": "Shauna Heck (2025)"},
    {"author": "Jane de la Vaud\u00e8re", "works": ["Les Demi-sexes"], "studied_by": "Islert (2025), Cl\u00e8re (2025)"},
    {"author": "Georges Eekhoud", "works": ["L'Autre vue (homosexuality)"], "studied_by": "Grommerch (2025)"},
    {"author": "Baudelaire", "works": ["Le Spleen de Paris (satire)"], "studied_by": "Patrick Th\u00e9riault (2025)"},
    {"author": "Olivier Cadiot / Pierre Alferi", "works": ["Revue de litt\u00e9rature g\u00e9n\u00e9rale (montage)"], "studied_by": "Huppe (2025), Wourm (2025)"},
    {"author": "Gr\u00e9gory Chatonsky", "works": ["Internes (GPT co-written)"], "studied_by": "Yves Citton (2025)"},
    {"author": "Sophie Divry, Sandra Lucbert, Nathalie Quintane", "works": ["Satirical montage"], "studied_by": "Saint-Amand (2025), Quintane (2025)"},
    {"author": "Karoline Georges", "works": ["Posthuman fiction"], "studied_by": "Laura Lafrance (2025)"},
    {"author": "P.K. Dick", "works": ['"The Golden Man"'], "studied_by": "Manuela Mohr (2025)"},
    {"author": "Alain Damasio", "works": ["Les Furtifs"], "studied_by": "Julien Tribott\u00e9 (2025)"},
    {"author": "Kole Omotoso", "works": ["The Combat"], "studied_by": "Verissimo (2025)"},
    {"author": "Asl\u0131 Erdo\u011fan", "works": ["The City in Crimson Cloak"], "studied_by": "Ali Kulez (2025)"},
    {"author": "May Ayim & Ada Diagne", "works": ["Black German poetry"], "studied_by": "Adrienne Merritt (2025)"},
    {"author": "Lydie Salvayre", "works": ["Pas Pleurer (Cry, Mother Spain)"], "studied_by": "Mats Haraldsen (2025)"},
    {"author": "B. Kucinski", "works": ["A nova ordem", "O colapso da nova ordem"], "studied_by": "Georg Wink (2026)"},
    {"author": "Francesca Melandri", "works": ["Sangue giusto"], "studied_by": "Guido Bartolini (2026)"},
    {"author": "Ricardo M. Rojas", "works": ["El se\u00f1or Robinson"], "studied_by": "Patrick Eser (2026)"},
    {"author": "Lauren Slater", "works": ["Lying (fictionality)"], "studied_by": "Mengchen Lang (2025)"},
    {"author": "Charles Yu", "works": ["How to Live Safely in a Science Fictional Universe"], "studied_by": "Daniel Punday (2025)"},
    {"author": "Willy Schumann", "works": ["Being Present (Hitler Youth memoir)"], "studied_by": "Anne Rothe (2009)"},
    {"author": "Ry Nikonova", "works": ["Samizdat journals Nomer/Transponans"], "studied_by": "Rebekah Smith (2025)"},
    {"author": "Marianne Hirsch", "works": ["Postmemory theory"], "studied_by": "Hirsch (2008) \u2014 self-authored"},
    {"author": "Marie-Pier Lafontaine", "works": ["Chienne (post-traumatic)"], "studied_by": "Gabriel Proulx (2025)"},
    {"author": "F\u00e9licit\u00e9 de Choiseul-Meuse", "works": ["Julie, ou j'ai sauv\u00e9 ma rose"], "studied_by": "M\u00e9lissa Thiriot (2025)"},
    {"author": "Don't Look Up (2021 film)", "works": ["Satirical metapolitics"], "studied_by": "Stefanie Sch\u00e4fer (2026)"},
    {"author": "Wordsworth", "works": ["Peter Bell (via Bateson)"], "studied_by": "Ramsey McGlazer (2025)"},
    {"author": "Huang Gongwang", "works": ["Dwelling in the Fuchun Mountains (scroll painting)"], "studied_by": "Chloe Estep (2025)"},
]
